sudo: false
dist: trusty
language: cpp

addons: 
  apt: 
    sources: 
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
    packages: 
      - g++-6
      - clang-4.0

matrix:
  - compiler: gcc
    env: COMPILER=g++-6
  - compiler: clang
    env: COMPILER=clang++4.0

before_script:
  - CMAKE_VERSION="cmake-3.8.1-Linux-x86_64"
  - wget "http://cmake.org/files/v3.8/$CMAKE_VERSION.tar.gz"
  - tar xf "$CMAKE_VERSION.tar.gz"
  - export CMAKE="$(pwd)/$CMAKE_VERSION/bin/cmake"
  - $CMAKE --version
script:
  - mkdir build
  - cd build
  - $CMAKE -DCMAKE_CXX_COMPILER=$COMPILER ..
  - $CMAKE --build .
